language: python

python:
    - "3.6.5"

before_script:
    - "pip3 install -r requirements.txt"

script:
    - "python3 douban_renting_house.py -r 'hangzhou' -s '租房' -l 1000"

after_script:
    - "echo ${?}"

